---
- hosts: controller
  tasks:
    - name: Setup tox role
      include_role:
        name: tox
      vars:
        tox_envlist: venv
        tox_install_siblings: false
        zuul_work_dir: "{{ zuul.projects['github.com/ansible/ansible-zuul-jobs'].src_dir }}"

    - name: Install binary dependencies from ansible/ansible-zuul-jobs
      include_role:
        name: bindep
      vars:
        bindep_dir: "{{ zuul.projects['github.com/ansible/ansible-zuul-jobs'].src_dir }}"

    - name: Fetch and install the artifacts
      import_role:
        name: deploy-artifacts
      when:
        - ansible_test_collections | default(False)
