---
vmware_ci_vcsa_services_disabled:
  - vmcam
  - vmware-imagebuilder
  - vmware-mbcs
  - vmware-netdumper
  - vmware-rbd-watchdog
  - vmware-vcha
  - vsan-dps
  - vsphere-client
  - vsphere-ui
vmware_ci_vcsa_services_enabled:
  - applmgmt
  - lwsmd
  - pschealth
  - vmafdd
  - vmcad
  - vmdird
  - vmdnsd
  - vmonapi
  - vmware-analytics
  - vmware-cis-license
  - vmware-cm
  - vmware-content-library
  - vmware-eam
  - vmware-perfcharts
  - vmware-pod
  - vmware-postgres-archiver
  - vmware-rhttpproxy
  - vmware-sca
  - vmware-sps
  - vmware-statsmonitor
  - vmware-sts-idmd
  - vmware-stsd
  - vmware-updatemgr
  - vmware-vapi-endpoint
  - vmware-vmon
  - vmware-vpostgres
  - vmware-vpxd
  - vmware-vpxd-svcs
  - vmware-vsan-health
  - vmware-vsm
