---
- hosts: controller
  tasks:
    - name: Ensure controller directory exists
      file:
        path: "{{ ansible_user_dir }}/zuul-output/logs/controller/"
        state: directory

    - name: Copy appliance inventory file
      shell: "cp {{ ansible_user_dir }}/inventory {{ ansible_user_dir }}/zuul-output/logs/controller/inventory"
