---
- hosts: controller
  tasks:
    - name: Setup tox role
      include_role:
        name: tox
      vars:
        tox_extra_args: "-vv -- ansible-playbook -v playbooks/ansible-test-network-integration-base/files/bootstrap-{{ ansible_test_network_integration }}.yaml"
        tox_install_siblings: false
        zuul_work_dir: "{{ zuul.projects['github.com/ansible/ansible-zuul-jobs'].src_dir }}"

    - name: Ensure remote NETCONF SSH host keys are known
      shell: "ssh-keyscan -t rsa -p 830 {{ hostvars[item].ansible_host }} >> ~/.ssh/known_hosts"
      with_inventory_hostnames: appliance
