---
- hosts: controller
  tasks:
    - name: Setup base test_options
      set_fact:
        _test_options: "--continue-on-error --diff --requirements"

    - name: Enable --no-temp-workdir for test_options
      set_fact:
        _test_options: "{{ _test_options }} --no-temp-workdir"
      when: zuul.projects['github.com/ansible/ansible'].checkout not in ["stable-2.6", "stable-2.7"]

    - name: Setup base target for ansible-test
      set_fact:
        _target: "{{ ansible_test_network_integration }}_.*"

    - name: Enable netconf_.* target for ansible-test
      set_fact:
        _target: "{{ _target }} netconf_.*"
      when: ansible_test_network_integration in ["iosxr", "junos"]

    - name: Run the integration test suite
      args:
        chdir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}"
        executable: /bin/bash
      shell: "source ~/venv/bin/activate; {{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}/bin/ansible-test network-integration {{ _test_options }} --python {{ ansible_test_python }} --inventory /home/zuul/inventory -vvvv {{ _target }}"
