---
- hosts: controller
  tasks:
    - name: Setup location of project
      set_fact:
        _test_location: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}"

    - name: Setup base test_options
      set_fact:
        _test_options: "--continue-on-error --diff --requirements"

    - name: Enable --no-temp-workdir for test_options
      set_fact:
        _test_options: "{{ _test_options }} --no-temp-workdir"
      when: zuul.projects['github.com/ansible/ansible'].checkout not in ["stable-2.6", "stable-2.7"]

    - copy:
        content: |
            [DEFAULT]
            vcenter_username: administrator@vsphere.local
            vcenter_password: !234AaAa56
            vcenter_hostname: {{ hostvars['vmware-vcsa-6.7.0']['nodepool']['interface_ip']}}
            vmware_validate_certs: false
        dest: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}/test/integration/cloud-config-vcenter.ini"

    - name: Run the integration test suite
      args:
        chdir: "{{ _test_location }}"
        executable: /bin/bash
      shell: "source ~/venv/bin/activate; {{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}/bin/ansible-test integration {{ _test_options }} --python {{ ansible_test_python }} -vvvv {{ ansible_test_integration_target }}"
      environment:
        VMWARE_TEST_PLATFORM: static
