---
- hosts: all
  tasks:
    - name: Generate version number for ansible collection
      args:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
      shell: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible-network/releases'].src_dir }}/.tox/venv/bin/python -W ignore {{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible-network/releases'].src_dir }}/.tox/venv/bin/generate-ansible-collection"
      register: _version

    - name: Confirm collection can be imported into galaxy
      args:
        chdir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible-network/releases'].src_dir }}"
      shell: "source .tox/venv/bin/activate; ./tools/validate-collection.sh {{ ansible_user_dir }}/downloads/{{ _version.stdout }}"
