---
- hosts: controller
  tasks:
    - name: Install binary dependencies
      include_role:
        name: bindep
      vars:
        bindep_dir: "{{ zuul.projects['github.com/ansible/ansible-zuul-jobs'].src_dir }}"

    - name: Run test-setup role
      include_role:
        name: test-setup

    - name: Wait 300 seconds for port tcp/22 on appliance
      wait_for:
        delay: 10
        host: "{{ hostvars[item].ansible_host }}"
        port: 22
        search_regex: SSH
      with_inventory_hostnames: appliance:openvswitch

    - name: Ensure remote SSH host keys are known
      shell: "ssh-keyscan {{ hostvars[item].ansible_host }} >> ~/.ssh/known_hosts"
      with_inventory_hostnames: appliance:openvswitch

    - name: Create /etc/ansible folder
      become: true
      file:
        path: /etc/ansible
        state: directory
        mode: 0755

    - name: Install ansible.cfg
      template:
        src: ansible.cfg.j2
        dest: ~/.ansible.cfg
        mode: 0644

    - name: Run write-inventory-fork role
      include_role:
        name: write-inventory-fork
        apply:
          become: true
      vars:
        write_inventory_dest: /etc/ansible/hosts
        write_inventory_exclude_hostvars:
          - ansible_connection
