---
- name: Build an ansible collection
  args:
    chdir: "{{ zuul_work_dir }}"
  command: "{{ ansible_galaxy_executable }} collection build --output-path {{ ansible_galaxy_output_path }} {{ ansible_galaxy_collection_path }}"
