---
- name: Identify the changed targets
  args:
    chdir: "{{ ansible_test_location }}"
    executable: /bin/bash
  shell: |
    for i in $(git diff origin/main --name-only|egrep '^plugins/.*.py'|xargs -r basename -s .py); do
      test -f tests/integration/targets/${i}/aliases && echo ${i}
    done
  register: _result
- set_fact:
    ansible_test_integration_targets: "{{ _result.stdout_lines|join(' ') }}"
