---
- name: Enable ARA callback plugin
  ini_file:
    path: "{{ _test_cfg_location }}"
    section: defaults
    option: callback_plugins
    value: "{{ ansible_test_venv_path }}/site-packages/ara/plugins/callbacks"

- name: Enable persistent connection logging
  ini_file:
    path: "{{ _test_cfg_location }}"
    section: persistent_connection
    option: log_messages
    value: true

- name: Set ansible log path
  ini_file:
    path: "{{ _test_cfg_location }}"
    section: defaults
    option: log_path
    value: ~/ansible-debug.txt
