---
- hosts: all
  tasks:
    - name: Ensure python3-wheel is installed
      become: true
      package:
        name: python3-wheel
        state: present

    - name: Run revoke-sudo role
      include_role:
        name: revoke-sudo
