---
- hosts: controller
  tasks:
    - name: Ensure sshpass is present
      become: true
      package:
        enablerepo: epel
        name: sshpass
        state: present

    - name: Setup tox role
      include_role:
        name: tox
      vars:
        tox_extra_args: -- ansible-playbook -v playbooks/ansible-cloud/vcsa-appliance/files/bootstrap.yaml
        tox_install_siblings: false
        zuul_work_dir: "{{ zuul.projects['github.com/ansible/ansible-zuul-jobs'].src_dir }}"

    - name: "wait for the vcenter service"
      uri:
        url: "https://{{ hostvars['vmware-vcsa-6.7.0']['nodepool']['interface_ip'] }}"
        validate_certs: false
        return_content: true
      register: result
      until:
        - "result.status == 200"
        - "'vmc-documentation-link' in result.content"
      retries: 100
      delay: 5
